// console.log(Math.PI);

let x = 5.954;
let y = 2.6;
let z = 3;
// x = Math.round(x);
// x = Math.floor(x);
// x = Math.ceil(x);
// x = Math.trunc(x);
// x = Math.pow(x, 7);
// x = Math.sqrt(x);
// x = Math.log(x);
// x = Math.sin(x);
// x = Math.cos(x);
// x = Math.tan(x);
// x = Math.abs(x);
// x = Math.sign(x);
// let maֶx= Math.max(x, y, z);
// let min = Math.min(x, y, z);
console.log(x);